-- =============================================================================
-- 01. Create PAY.PAY_ELEMENT_ELIG_PROFILE_ELEMENTS
-- =============================================================================

SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count
    FROM all_tables
   WHERE owner = 'PAY'
     AND table_name = 'PAY_ELEMENT_ELIG_PROFILE_ELEMENTS';

  IF l_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('PAY_ELEMENT_ELIG_PROFILE_ELEMENTS already exists.');
    RETURN;
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE PAY.PAY_ELEMENT_ELIG_PROFILE_ELEMENTS (
      PROFILE_ELEMENT_ID    NUMBER          NOT NULL,
      PROFILE_ELEMENT_GUID  RAW(16)         DEFAULT SYS_GUID() NOT NULL,
      PROFILE_ID            NUMBER          NOT NULL,
      ELEMENT_ID            NUMBER          NOT NULL,
      CREATED_BY            VARCHAR2(100)   NOT NULL,
      CREATION_DATE         DATE            NOT NULL,
      LAST_UPDATED_BY       VARCHAR2(100)   NOT NULL,
      LAST_UPDATE_DATE      DATE            NOT NULL,
      CONSTRAINT PAY_EEL_PROF_ELEMS_PK PRIMARY KEY (PROFILE_ELEMENT_ID),
      CONSTRAINT PAY_EEL_PROF_ELEMS_GUID_UK UNIQUE (PROFILE_ELEMENT_GUID),
      CONSTRAINT PAY_EEL_PROF_ELEMS_UK1 UNIQUE (PROFILE_ID, ELEMENT_ID),
      CONSTRAINT PAY_EEL_PROF_ELEMS_PROFILE_FK
        FOREIGN KEY (PROFILE_ID)
        REFERENCES PAY.PAY_ELEMENT_ELIG_PROFILES (PROFILE_ID)
        ON DELETE CASCADE,
      CONSTRAINT PAY_EEL_PROF_ELEMS_ELEMENT_FK
        FOREIGN KEY (ELEMENT_ID)
        REFERENCES PAY.PAY_ELEMENTS (ELEMENT_ID)
    )';

  DBMS_OUTPUT.PUT_LINE('Created PAY_ELEMENT_ELIG_PROFILE_ELEMENTS.');
END;
/

PROMPT 01_create_link_table.sql completed.
