/**
 * SQL for job-posting employer-info resolution.
 * Prefer REC.V_JOB_POSTING_EMPLOYER_INFO (see sql/create_rec_v_job_posting_employer_info.sql).
 * Fallback mirrors the view when it is not deployed.
 */

import { JOB_POSTING_EMPLOYER_INFO_VIEW } from './recJobPostingEmployerInfoConstants.js';

/** View exposes POSTING_GUID as hex VARCHAR2 (RAWTOHEX). */
export const VIEW_SELECT_BY_HEX = `
  SELECT v.*
  FROM ${JOB_POSTING_EMPLOYER_INFO_VIEW} v
  WHERE UPPER(v.POSTING_GUID) = :posting_guid
  FETCH FIRST 1 ROW ONLY
`;

/**
 * Same business rules as the view: posting → requisition → CONNECT BY COMPANY
 * → COMPANY_LEVEL employer info, else ENTERPRISE_LEVEL.
 * Binds :posting_guid as RAW(16) Buffer.
 */
export const FALLBACK_SELECT_BY_RAW = `
WITH posting_req AS (
  SELECT
    jp.POSTING_ID,
    jp.POSTING_GUID,
    jp.ENTERPRISE_ID,
    jp.REQUISITION_ID,
    r.ORG_UNIT_ID AS REQUISITION_ORG_UNIT_ID,
    CASE
      WHEN jp.REQUISITION_ID IS NULL THEN 'N'
      WHEN r.REQUISITION_ID IS NULL THEN 'N'
      ELSE 'Y'
    END AS REQUISITION_FOUND
  FROM REC.REC_JOB_POSTINGS jp
  LEFT JOIN REC.REC_REQUISITION r
    ON r.REQUISITION_ID = jp.REQUISITION_ID
   AND r.ENTERPRISE_ID = jp.ENTERPRISE_ID
  WHERE jp.POSTING_GUID = :posting_guid
),
company_resolved AS (
  SELECT
    pr.*,
    co.ORG_UNIT_ID AS COMPANY_ID,
    co.ORG_UNIT_CODE AS COMPANY_CODE,
    co.ORG_UNIT_NAME_EN AS COMPANY_NAME,
    co.ORG_UNIT_NAME_AR AS COMPANY_NAME_AR
  FROM posting_req pr
  LEFT JOIN LATERAL (
    SELECT
      h.ORG_UNIT_ID,
      h.ORG_UNIT_CODE,
      h.ORG_UNIT_NAME_EN,
      h.ORG_UNIT_NAME_AR
    FROM (
      SELECT
        ou.ORG_UNIT_ID,
        ou.ORG_UNIT_CODE,
        ou.ORG_UNIT_NAME_EN,
        ou.ORG_UNIT_NAME_AR,
        ou.LEVEL_CODE,
        LEVEL AS HIER_LEVEL
      FROM ENT.ORG_UNITS ou
      WHERE ou.ENTERPRISE_ID = pr.ENTERPRISE_ID
      START WITH ou.ORG_UNIT_ID = pr.REQUISITION_ORG_UNIT_ID
             AND ou.ENTERPRISE_ID = pr.ENTERPRISE_ID
      CONNECT BY NOCYCLE
        PRIOR ou.PARENT_ORG_UNIT_ID = ou.ORG_UNIT_ID
        AND PRIOR ou.ENTERPRISE_ID = ou.ENTERPRISE_ID
    ) h
    WHERE h.LEVEL_CODE = 'COMPANY'
    ORDER BY h.HIER_LEVEL
    FETCH FIRST 1 ROW ONLY
  ) co ON 1 = 1
)
SELECT
  RAWTOHEX(cr.POSTING_GUID) AS POSTING_GUID,
  cr.ENTERPRISE_ID,
  cr.REQUISITION_ID,
  CASE
    WHEN cr.REQUISITION_ORG_UNIT_ID IS NULL THEN NULL
    ELSE RAWTOHEX(cr.REQUISITION_ORG_UNIT_ID)
  END AS REQUISITION_ORG_UNIT_ID,
  cr.REQUISITION_FOUND,
  CASE WHEN cr.COMPANY_ID IS NULL THEN NULL ELSE RAWTOHEX(cr.COMPANY_ID) END AS COMPANY_ID,
  cr.COMPANY_CODE,
  cr.COMPANY_NAME,
  cr.COMPANY_NAME_AR,
  CASE
    WHEN cei.EMPLOYER_INFO_ID IS NOT NULL THEN 'COMPANY_LEVEL'
    WHEN eei.EMPLOYER_INFO_ID IS NOT NULL THEN 'ENTERPRISE_LEVEL'
    ELSE NULL
  END AS EMPLOYER_INFO_SOURCE,
  NVL(cei.EMPLOYER_INFO_ID, eei.EMPLOYER_INFO_ID) AS EMPLOYER_INFO_ID,
  CASE
    WHEN NVL(cei.EMPLOYER_INFO_GUID, eei.EMPLOYER_INFO_GUID) IS NULL THEN NULL
    ELSE RAWTOHEX(NVL(cei.EMPLOYER_INFO_GUID, eei.EMPLOYER_INFO_GUID))
  END AS EMPLOYER_INFO_GUID,
  NVL(cei.EMPLOYEE_INFO, eei.EMPLOYEE_INFO) AS EMPLOYEE_INFO,
  NVL(cei.INFORMATION, eei.INFORMATION) AS INFORMATION,
  NVL(cei.INDUSTRY, eei.INDUSTRY) AS INDUSTRY,
  NVL(cei.ABOUT_COMPANY, eei.ABOUT_COMPANY) AS ABOUT_COMPANY,
  CASE
    WHEN NVL(cei.EMPLOYER_INFO_ID, eei.EMPLOYER_INFO_ID) IS NULL THEN 'N'
    WHEN cei.EMPLOYER_INFO_ID IS NOT NULL AND cei.LOGO IS NOT NULL THEN 'Y'
    WHEN cei.EMPLOYER_INFO_ID IS NOT NULL THEN 'N'
    WHEN eei.LOGO IS NOT NULL THEN 'Y'
    ELSE 'N'
  END AS LOGO_AVAILABLE,
  NVL(cei.LOGO_FILE_NAME, eei.LOGO_FILE_NAME) AS LOGO_FILE_NAME,
  NVL(cei.LOGO_MIME_TYPE, eei.LOGO_MIME_TYPE) AS LOGO_MIME_TYPE,
  NVL(cei.ACTIVE_FLAG, eei.ACTIVE_FLAG) AS ACTIVE_FLAG
FROM company_resolved cr
LEFT JOIN REC.EMPLOYER_INFO cei
  ON cei.ENTERPRISE_ID = cr.ENTERPRISE_ID
 AND cei.ASSIGNMENT_TYPE = 'COMPANY_LEVEL'
 AND cei.COMPANY_ID = cr.COMPANY_ID
 AND NVL(cei.ACTIVE_FLAG, 'N') = 'Y'
LEFT JOIN REC.EMPLOYER_INFO eei
  ON eei.ENTERPRISE_ID = cr.ENTERPRISE_ID
 AND eei.ASSIGNMENT_TYPE = 'ENTERPRISE_LEVEL'
 AND eei.COMPANY_ID IS NULL
 AND NVL(eei.ACTIVE_FLAG, 'N') = 'Y'
FETCH FIRST 1 ROW ONLY
`;
