-- COMP.COMP_SALARY_STRUCTURE_JSON_V (single source for list + detail in Node)
--
-- List: GET /api/comp/salary-structures
--   SELECT header columns (STRUCTURE_ID, STRUCTURE_GUID, ENTERPRISE_ID, STRUCTURE_CODE,
--   STRUCTURE_NAME, STRUCTURE_TYPE_CODE, LOCATION_OBJ, ACTIVE_FLAG, CREATED_BY, CREATION_DATE,
--   LAST_UPDATED_BY, LAST_UPDATE_DATE)
--   + COUNT(*) + OFFSET/FETCH (see compSalaryStructureJsonViewModel.js).
--
--   LOCATION_OBJ must be JSON (or CLOB/VARCHAR2 holding JSON) shaped like a comp lookup row:
--   lookup_value_id, lookup_value_guid, lookup_type_id, tenant_id, value_code, value_name,
--   display_sequence, active_flag, type_code, type_name, type_description.
--
-- Detail: GET /api/comp/salary-structures-details?enterprise_id=&structure_id=|structure_guid=
--   Full row including STRUCTURE_OBJ, *_JSON columns (see buildJsonViewDetailSelectSql).
--
-- Optional env:
--   COMP_SALARY_STRUCTURE_ENTERPRISE_COL=TENANT_ID
--   COMP_SALARY_STRUCTURE_JSON_V_ACTIVE_COL=STRUCTURE_ACTIVE_FLAG
--   COMP_SALARY_STRUCTURE_JSON_V_GUID_FORMAT=VARCHAR  (if STRUCTURE_GUID is not RAW)
--   COMP_SALARY_STRUCTURE_JSON_V_TYPE_LOCATION_COLS=1
--     Set after the view exposes STRUCTURE_TYPE_CODE and LOCATION_OBJ; if unset, Node omits them
--     from SELECT (avoids ORA-00904) and API returns null / {} for those fields on list + detail.
--   COMP_SALARY_STRUCTURE_JSON_V_LIST_INCLUDE_STRUCTURE_OBJ=1|0
--     When TYPE_LOCATION_COLS is off, list SELECT includes STRUCTURE_OBJ by default so GET …/salary-structures
--     can mirror detail top-level structure_type_code / location_obj from STRUCTURE_OBJ. Set =0 to omit
--     STRUCTURE_OBJ from list (lighter query; top-level type/location only from view columns). Set =1 to
--     force STRUCTURE_OBJ on list even when TYPE_LOCATION_COLS=1 (e.g. view columns null).
