-- Add stage columns to REC.V_JOB_OFFERS list view (run as REC schema owner).

CREATE OR REPLACE VIEW REC.V_JOB_OFFERS AS
SELECT
  o.OFFER_GUID,
  o.OFFER_NUMBER,
  a.APPLICATION_GUID,
  a.APPLICATION_NUMBER,
  o.CANDIDATE_GUID,
  TRIM(c.FIRST_NAME || ' ' || NVL(c.MIDDLE_NAME, '') || ' ' || c.LAST_NAME) AS CANDIDATE_NAME,
  o.POSTING_ID,
  o.JOB_TITLE,
  p.POSITION_TITLE_EN AS POSITION_NAME,
  ou.ORG_UNIT_NAME_EN AS DEPARTMENT_NAME,
  o.LOCATION,
  o.START_DATE,
  o.OFFER_DATE,
  o.EXPIRY_DATE,
  o.STAGE,
  o.STATUS_CODE,
  o.STAGE_DESCRIPTION,
  o.ENTERPRISE_ID
FROM REC.REC_JOB_OFFERS o
LEFT JOIN REC.REC_APPLICATIONS a
  ON a.APPLICATION_ID = o.APPLICATION_ID
 AND a.ENTERPRISE_ID = o.ENTERPRISE_ID
LEFT JOIN REC.CANDIDATES c
  ON c.CANDIDATE_GUID = o.CANDIDATE_GUID
 AND c.ENTERPRISE_ID = o.ENTERPRISE_ID
LEFT JOIN ENT.POSITIONS p
  ON p.POSITION_ID = o.POSITION_ID
LEFT JOIN ENT.ORG_UNITS ou
  ON ou.ORG_UNIT_ID = o.DEPARTMENT_ID;
