-- =============================================================================
-- 01. Drop previous eligibility profile implementations (old + element elig)
-- Safe to re-run: ignores missing objects.
-- =============================================================================

SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

BEGIN
  -- Old PAY_ELIGIBILITY_PROFILES implementation
  FOR r IN (
    SELECT object_name, object_type
      FROM all_objects
     WHERE owner = 'PAY'
       AND object_name IN (
         'V_PAY_ELIGIBILITY_PROFILE_CRITERIA',
         'V_PAY_ELIGIBILITY_PROFILES_FULL',
         'V_PAY_ELIGIBILITY_PROFILES',
         'PAY_ELIGIBILITY_PROFILES_PKG',
         'PAY_ELIGIBILITY_PROFILE_CRITERIA',
         'PAY_ELIGIBILITY_PROFILES'
       )
  ) LOOP
  BEGIN
    IF r.object_type = 'PACKAGE BODY' THEN
      EXECUTE IMMEDIATE 'DROP PACKAGE BODY PAY.' || r.object_name;
    ELSIF r.object_type = 'PACKAGE' THEN
      EXECUTE IMMEDIATE 'DROP PACKAGE PAY.' || r.object_name;
    ELSIF r.object_type = 'VIEW' THEN
      EXECUTE IMMEDIATE 'DROP VIEW PAY.' || r.object_name;
    ELSIF r.object_type = 'TABLE' THEN
      EXECUTE IMMEDIATE 'DROP TABLE PAY.' || r.object_name || ' CASCADE CONSTRAINTS PURGE';
    END IF;
    DBMS_OUTPUT.PUT_LINE('Dropped PAY.' || r.object_name || ' (' || r.object_type || ')');
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Skip PAY.' || r.object_name || ': ' || SQLERRM);
  END;
  END LOOP;

  -- PAY Element Eligibility Profiles (redeploy)
  BEGIN EXECUTE IMMEDIATE 'DROP VIEW PAY.V_PAY_ELEMENT_ELIG_PROFILES'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE BODY PAY.PAY_ELEMENT_ELIG_PROFILES_PKG'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PAY.PAY_ELEMENT_ELIG_PROFILES_PKG'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER PAY.PAY_EEL_PROF_RULES_BIU_TRG'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER PAY.PAY_EEL_PROFILES_BIU_TRG'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAY.PAY_ELEMENT_ELIG_PROFILE_RULES CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAY.PAY_ELEMENT_ELIG_PROFILES CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PAY.PAY_ELEMENT_ELIG_PROF_RULES_S'; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PAY.PAY_ELEMENT_ELIG_PROFILES_S'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

PROMPT 01_drop_previous_implementation.sql completed.
