-- =============================================================================
-- 03. Create PAY.PAY_ELEMENT_ELIG_PROFILE_RULES
-- =============================================================================

SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count
    FROM all_tables
   WHERE owner = 'PAY'
     AND table_name = 'PAY_ELEMENT_ELIG_PROFILE_RULES';

  IF l_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('PAY_ELEMENT_ELIG_PROFILE_RULES already exists.');
    RETURN;
  END IF;

  EXECUTE IMMEDIATE '
    CREATE TABLE PAY.PAY_ELEMENT_ELIG_PROFILE_RULES (
      PROFILE_RULE_ID       NUMBER          NOT NULL,
      PROFILE_RULE_GUID     RAW(16)         DEFAULT SYS_GUID() NOT NULL,
      PROFILE_ID            NUMBER          NOT NULL,
      ELIGIBILITY_RULE_ID   NUMBER          NOT NULL,
      CREATED_BY            VARCHAR2(100)   NOT NULL,
      CREATION_DATE         DATE            NOT NULL,
      LAST_UPDATED_BY       VARCHAR2(100)   NOT NULL,
      LAST_UPDATE_DATE      DATE            NOT NULL,
      CONSTRAINT PAY_EEL_PROF_RULES_PK PRIMARY KEY (PROFILE_RULE_ID),
      CONSTRAINT PAY_EEL_PROF_RULES_GUID_UK UNIQUE (PROFILE_RULE_GUID),
      CONSTRAINT PAY_EEL_PROF_RULES_UK1 UNIQUE (PROFILE_ID, ELIGIBILITY_RULE_ID),
      CONSTRAINT PAY_EEL_PROF_RULES_PROFILE_FK
        FOREIGN KEY (PROFILE_ID)
        REFERENCES PAY.PAY_ELEMENT_ELIG_PROFILES (PROFILE_ID)
        ON DELETE CASCADE,
      CONSTRAINT PAY_EEL_PROF_RULES_RULE_FK
        FOREIGN KEY (ELIGIBILITY_RULE_ID)
        REFERENCES PAY.PAY_ELEMENT_ELIGIBILITY_RULES (ELIGIBILITY_RULE_ID)
    )';

  DBMS_OUTPUT.PUT_LINE('Created PAY_ELEMENT_ELIG_PROFILE_RULES.');
END;
/

PROMPT 03_create_child_profile_rules_table.sql completed.
