CREATE OR REPLACE PACKAGE PAY.PAY_ELEMENT_FREQUENCY_RULES_PKG AS

  PROCEDURE CREATE_FREQUENCY_RULE (
      P_PAYLOAD_JSON          IN  CLOB,
      P_CREATED_BY            IN  VARCHAR2,
      P_FREQUENCY_RULE_ID     OUT NUMBER,
      P_FREQUENCY_RULE_GUID   OUT VARCHAR2,
      P_STATUS                OUT VARCHAR2,
      P_MESSAGE               OUT VARCHAR2
  );

  PROCEDURE UPDATE_FREQUENCY_RULE (
      P_FREQUENCY_RULE_GUID   IN  VARCHAR2,
      P_PAYLOAD_JSON          IN  CLOB,
      P_UPDATED_BY            IN  VARCHAR2,
      P_STATUS                OUT VARCHAR2,
      P_MESSAGE               OUT VARCHAR2
  );

  PROCEDURE DELETE_FREQUENCY_RULE (
      P_FREQUENCY_RULE_GUID   IN  VARCHAR2,
      P_DELETED_BY            IN  VARCHAR2,
      P_STATUS                OUT VARCHAR2,
      P_MESSAGE               OUT VARCHAR2
  );

END PAY_ELEMENT_FREQUENCY_RULES_PKG;
/
