CREATE OR REPLACE PACKAGE BODY PAY.PAY_ELEMENT_FREQUENCY_RULES_PKG AS

  FUNCTION GUID_TO_RAW(P_GUID IN VARCHAR2) RETURN RAW IS
  BEGIN
    IF P_GUID IS NULL OR TRIM(P_GUID) IS NULL THEN
      RETURN NULL;
    END IF;
    RETURN HEXTORAW(REPLACE(UPPER(TRIM(P_GUID)), '-', ''));
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20802, 'Invalid frequency rule GUID format.');
  END GUID_TO_RAW;

  FUNCTION RAW_TO_GUID(P_RAW IN RAW) RETURN VARCHAR2 IS
  BEGIN
    IF P_RAW IS NULL THEN
      RETURN NULL;
    END IF;
    RETURN LOWER(RAWTOHEX(P_RAW));
  END RAW_TO_GUID;

  FUNCTION FRIENDLY_ERROR RETURN VARCHAR2 IS
  BEGIN
    IF SQLCODE BETWEEN -20999 AND -20000 THEN
      RETURN REGEXP_REPLACE(SQLERRM, '^ORA-[0-9]+: ', '');
    END IF;
    RETURN SQLERRM;
  END FRIENDLY_ERROR;

  PROCEDURE CREATE_FREQUENCY_RULE (
      P_PAYLOAD_JSON          IN  CLOB,
      P_CREATED_BY            IN  VARCHAR2,
      P_FREQUENCY_RULE_ID     OUT NUMBER,
      P_FREQUENCY_RULE_GUID   OUT VARCHAR2,
      P_STATUS                OUT VARCHAR2,
      P_MESSAGE               OUT VARCHAR2
  ) IS
    L_ELEMENT_ID NUMBER;
    L_COUNT      NUMBER;
    L_GUID_RAW   RAW(16);
  BEGIN
    P_STATUS  := 'ERROR';
    P_MESSAGE := NULL;

    IF P_PAYLOAD_JSON IS NULL OR TRIM(P_PAYLOAD_JSON) IS NULL THEN
      RAISE_APPLICATION_ERROR(-20812, 'Payload JSON is required.');
    END IF;

    L_ELEMENT_ID := JSON_VALUE(P_PAYLOAD_JSON, '$.element_id' RETURNING NUMBER NULL ON ERROR);

    IF L_ELEMENT_ID IS NULL THEN
      RAISE_APPLICATION_ERROR(-20803, 'Element is required.');
    END IF;

    SELECT COUNT(*)
      INTO L_COUNT
      FROM PAY.PAY_ELEMENTS
     WHERE ELEMENT_ID = L_ELEMENT_ID;

    IF L_COUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20805, 'Selected element does not exist.');
    END IF;

    SELECT COUNT(*)
      INTO L_COUNT
      FROM PAY.PAY_ELEMENT_FREQUENCY_RULES
     WHERE ELEMENT_ID = L_ELEMENT_ID;

    IF L_COUNT > 0 THEN
      RAISE_APPLICATION_ERROR(-20806, 'Frequency rule already exists for this element.');
    END IF;

    INSERT INTO PAY.PAY_ELEMENT_FREQUENCY_RULES (
        ELEMENT_ID,
        FREQUENCY_TYPE_CODE,
        FREQUENCY_FORMULA,
        EFFECTIVE_DATE,
        CREATED_BY,
        CREATION_DATE
    )
    VALUES (
        L_ELEMENT_ID,
        JSON_VALUE(P_PAYLOAD_JSON, '$.frequency_type_code' RETURNING VARCHAR2 NULL ON ERROR),
        JSON_VALUE(P_PAYLOAD_JSON, '$.frequency_formula' RETURNING VARCHAR2 NULL ON ERROR),
        TO_DATE(JSON_VALUE(P_PAYLOAD_JSON, '$.effective_date' RETURNING VARCHAR2 NULL ON ERROR), 'YYYY-MM-DD'),
        NVL(NULLIF(TRIM(P_CREATED_BY), ''), 'SYSTEM'),
        SYSDATE
    )
    RETURNING FREQUENCY_RULE_ID, FREQUENCY_RULE_GUID
      INTO P_FREQUENCY_RULE_ID, L_GUID_RAW;

    P_FREQUENCY_RULE_GUID := RAW_TO_GUID(L_GUID_RAW);
    P_STATUS              := 'SUCCESS';
    P_MESSAGE             := 'Frequency rule created successfully.';

  EXCEPTION
    WHEN OTHERS THEN
      P_STATUS  := 'ERROR';
      P_MESSAGE := FRIENDLY_ERROR;
  END CREATE_FREQUENCY_RULE;

  PROCEDURE UPDATE_FREQUENCY_RULE (
      P_FREQUENCY_RULE_GUID   IN  VARCHAR2,
      P_PAYLOAD_JSON          IN  CLOB,
      P_UPDATED_BY            IN  VARCHAR2,
      P_STATUS                OUT VARCHAR2,
      P_MESSAGE               OUT VARCHAR2
  ) IS
    L_GUID_RAW RAW(16);
    L_ID       NUMBER;
    L_TYPE     VARCHAR2(30);
    L_FORMULA  VARCHAR2(4000);
    L_DATE     DATE;
  BEGIN
    P_STATUS  := 'ERROR';
    P_MESSAGE := NULL;

    IF P_FREQUENCY_RULE_GUID IS NULL OR TRIM(P_FREQUENCY_RULE_GUID) IS NULL THEN
      RAISE_APPLICATION_ERROR(-20801, 'Frequency rule GUID is required.');
    END IF;

    IF P_PAYLOAD_JSON IS NULL OR TRIM(P_PAYLOAD_JSON) IS NULL THEN
      RAISE_APPLICATION_ERROR(-20812, 'Payload JSON is required.');
    END IF;

    L_GUID_RAW := GUID_TO_RAW(P_FREQUENCY_RULE_GUID);

    SELECT FREQUENCY_RULE_ID,
           FREQUENCY_TYPE_CODE,
           FREQUENCY_FORMULA,
           EFFECTIVE_DATE
      INTO L_ID, L_TYPE, L_FORMULA, L_DATE
      FROM PAY.PAY_ELEMENT_FREQUENCY_RULES
     WHERE FREQUENCY_RULE_GUID = L_GUID_RAW;

    IF JSON_EXISTS(P_PAYLOAD_JSON, '$.frequency_type_code') THEN
      L_TYPE := JSON_VALUE(P_PAYLOAD_JSON, '$.frequency_type_code' RETURNING VARCHAR2 NULL ON ERROR);
    END IF;

    IF JSON_EXISTS(P_PAYLOAD_JSON, '$.frequency_formula') THEN
      L_FORMULA := JSON_VALUE(P_PAYLOAD_JSON, '$.frequency_formula' RETURNING VARCHAR2 NULL ON ERROR);
    END IF;

    IF JSON_EXISTS(P_PAYLOAD_JSON, '$.effective_date') THEN
      L_DATE := TO_DATE(
        JSON_VALUE(P_PAYLOAD_JSON, '$.effective_date' RETURNING VARCHAR2 NULL ON ERROR),
        'YYYY-MM-DD'
      );
    END IF;

    UPDATE PAY.PAY_ELEMENT_FREQUENCY_RULES
       SET FREQUENCY_TYPE_CODE = L_TYPE,
           FREQUENCY_FORMULA   = L_FORMULA,
           EFFECTIVE_DATE      = L_DATE,
           LAST_UPDATED_BY     = NVL(NULLIF(TRIM(P_UPDATED_BY), ''), 'SYSTEM'),
           LAST_UPDATE_DATE    = SYSDATE
     WHERE FREQUENCY_RULE_ID = L_ID;

    P_STATUS  := 'SUCCESS';
    P_MESSAGE := 'Frequency rule updated successfully.';

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      P_STATUS  := 'ERROR';
      P_MESSAGE := 'Frequency rule not found.';
    WHEN OTHERS THEN
      P_STATUS  := 'ERROR';
      P_MESSAGE := FRIENDLY_ERROR;
  END UPDATE_FREQUENCY_RULE;

  PROCEDURE DELETE_FREQUENCY_RULE (
      P_FREQUENCY_RULE_GUID   IN  VARCHAR2,
      P_DELETED_BY            IN  VARCHAR2,
      P_STATUS                OUT VARCHAR2,
      P_MESSAGE               OUT VARCHAR2
  ) IS
    L_GUID_RAW RAW(16);
    L_ID       NUMBER;
  BEGIN
    P_STATUS  := 'ERROR';
    P_MESSAGE := NULL;

    IF P_FREQUENCY_RULE_GUID IS NULL OR TRIM(P_FREQUENCY_RULE_GUID) IS NULL THEN
      RAISE_APPLICATION_ERROR(-20801, 'Frequency rule GUID is required.');
    END IF;

    L_GUID_RAW := GUID_TO_RAW(P_FREQUENCY_RULE_GUID);

    SELECT FREQUENCY_RULE_ID
      INTO L_ID
      FROM PAY.PAY_ELEMENT_FREQUENCY_RULES
     WHERE FREQUENCY_RULE_GUID = L_GUID_RAW;

    DELETE FROM PAY.PAY_ELEMENT_FREQUENCY_RULES
     WHERE FREQUENCY_RULE_ID = L_ID;

    P_STATUS  := 'SUCCESS';
    P_MESSAGE := 'Frequency rule deleted successfully.';

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      P_STATUS  := 'ERROR';
      P_MESSAGE := 'Frequency rule not found.';
    WHEN OTHERS THEN
      P_STATUS  := 'ERROR';
      P_MESSAGE := FRIENDLY_ERROR;
  END DELETE_FREQUENCY_RULE;

END PAY_ELEMENT_FREQUENCY_RULES_PKG;
/
