-- =============================================================================
-- REC.CANDIDATE_INTERVIEW_FEEDBACK — structured interview evaluation storage
-- Run as REC (or ADMIN with privileges on REC objects).
-- Safe to re-run: skips CREATE TABLE if the table already exists.
-- =============================================================================

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_cnt
      FROM all_tables
     WHERE owner = 'REC'
       AND table_name = 'CANDIDATE_INTERVIEW_FEEDBACK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE REC.CANDIDATE_INTERVIEW_FEEDBACK (
                FEEDBACK_ID         NUMBER
                                    GENERATED BY DEFAULT ON NULL AS IDENTITY,
                FEEDBACK_GUID       RAW(16)       DEFAULT SYS_GUID() NOT NULL,
                ENTERPRISE_ID       NUMBER        NOT NULL,
                INTERVIEW_ID        NUMBER        NOT NULL,
                OVERALL_RATING      NUMBER        NOT NULL,
                TECHNICAL_SKILLS    VARCHAR2(50),
                COMMUNICATION       VARCHAR2(50),
                CULTURE_FIT         VARCHAR2(50),
                RECOMMENDATION      VARCHAR2(50)  NOT NULL,
                DETAILED_COMMENTS   VARCHAR2(4000),
                ACTIVE_FLAG         VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
                CREATED_BY          VARCHAR2(100) NOT NULL,
                CREATION_DATE       DATE          DEFAULT SYSDATE NOT NULL,
                LAST_UPDATED_BY     VARCHAR2(100) NOT NULL,
                LAST_UPDATE_DATE    DATE          DEFAULT SYSDATE NOT NULL,
                CONSTRAINT CANDIDATE_INTERVIEW_FEEDBACK_PK
                    PRIMARY KEY (FEEDBACK_ID),
                CONSTRAINT CANDIDATE_INTERVIEW_FEEDBACK_UK1
                    UNIQUE (ENTERPRISE_ID, INTERVIEW_ID),
                CONSTRAINT CANDIDATE_INTERVIEW_FEEDBACK_UK2
                    UNIQUE (FEEDBACK_GUID),
                CONSTRAINT CANDIDATE_INTERVIEW_FEEDBACK_CK1
                    CHECK (OVERALL_RATING BETWEEN 1 AND 5),
                CONSTRAINT CANDIDATE_INTERVIEW_FEEDBACK_CK2
                    CHECK (ACTIVE_FLAG IN ('Y', 'N')),
                CONSTRAINT CANDIDATE_INTERVIEW_FEEDBACK_FK1
                    FOREIGN KEY (INTERVIEW_ID)
                    REFERENCES REC.CANDIDATE_INTERVIEWS (INTERVIEW_ID)
            )
        ]';

        EXECUTE IMMEDIATE '
            CREATE INDEX REC.CANDIDATE_INTERVIEW_FEEDBACK_N1
                ON REC.CANDIDATE_INTERVIEW_FEEDBACK (ENTERPRISE_ID, INTERVIEW_ID)';

        EXECUTE IMMEDIATE '
            CREATE INDEX REC.CANDIDATE_INTERVIEW_FEEDBACK_N2
                ON REC.CANDIDATE_INTERVIEW_FEEDBACK (INTERVIEW_ID)';
    END IF;
END;
/
