-- =============================================================================
-- PAY.V_PAY_ELEMENT_SCOPE_RULES — element scope rule list/detail view
-- Sources: PAY.PAY_ELEMENT_SCOPE_RULES, PAY.PAY_ELEMENTS, PAY.PAYROLL_DEFINITIONS,
--          ENT.ORG_UNITS, ENT.GRADES, ENT.POSITIONS
-- Run as PAY (or ADMIN with privileges on PAY / ENT objects).
-- =============================================================================

CREATE OR REPLACE VIEW PAY.V_PAY_ELEMENT_SCOPE_RULES AS
SELECT
    S.SCOPE_RULE_ID,
    RAWTOHEX(S.SCOPE_RULE_GUID) AS SCOPE_RULE_GUID,

    S.ELEMENT_ID,
    RAWTOHEX(E.ELEMENT_GUID) AS ELEMENT_GUID,
    E.ELEMENT_CODE,
    E.ELEMENT_NAME,
    E.ENTERPRISE_ID,
    E.CLASSIFICATION_CODE,
    E.CATEGORY_CODE,

    S.SCOPE_LEVEL_CODE,

    S.PAYROLL_ID,
    P.PAYROLL_CODE,
    P.PAYROLL_NAME,

    RAWTOHEX(S.LEGAL_EMPLOYER_ID) AS LEGAL_EMPLOYER_GUID,
    LE.ORG_UNIT_CODE AS LEGAL_EMPLOYER_CODE,
    LE.ORG_UNIT_NAME_EN AS LEGAL_EMPLOYER_NAME,

    RAWTOHEX(S.ORG_UNIT_ID) AS ORG_UNIT_GUID,
    OU.ORG_UNIT_CODE,
    OU.ORG_UNIT_NAME_EN AS ORG_UNIT_NAME,

    S.GRADE_ID,
    G.GRADE_NUMBER,
    G.DESCRIPTION AS GRADE_NAME,

    RAWTOHEX(S.POSITION_ID) AS POSITION_GUID,
    POS.POSITION_CODE,
    POS.POSITION_TITLE_EN AS POSITION_NAME,

    S.CREATED_BY,
    S.CREATION_DATE,
    S.LAST_UPDATED_BY,
    S.LAST_UPDATE_DATE

FROM PAY.PAY_ELEMENT_SCOPE_RULES S
INNER JOIN PAY.PAY_ELEMENTS E
        ON E.ELEMENT_ID = S.ELEMENT_ID
LEFT JOIN PAY.PAYROLL_DEFINITIONS P
       ON P.PAYROLL_ID = S.PAYROLL_ID
LEFT JOIN ENT.ORG_UNITS LE
       ON LE.ORG_UNIT_ID = S.LEGAL_EMPLOYER_ID
LEFT JOIN ENT.ORG_UNITS OU
       ON OU.ORG_UNIT_ID = S.ORG_UNIT_ID
LEFT JOIN ENT.GRADES G
       ON G.GRADE_ID = S.GRADE_ID
LEFT JOIN ENT.POSITIONS POS
       ON POS.POSITION_ID = S.POSITION_ID;
