-- Fix PAY.V_PAYROLL_DEFINITIONS
-- ENT.ORG_UNITS uses ORG_UNIT_NAME_EN (not ORG_UNIT_NAME).

CREATE OR REPLACE VIEW PAY.V_PAYROLL_DEFINITIONS AS
SELECT
    PD.PAYROLL_ID,
    LOWER(RAWTOHEX(PD.PAYROLL_GUID)) AS PAYROLL_GUID,
    PD.ENTERPRISE_ID,
    PD.PAYROLL_NAME,
    PD.PAYROLL_CODE,
    PD.PAYROLL_CODE || ' - ' || PD.PAYROLL_NAME AS PAYROLL_DISPLAY,
    PD.EFFECTIVE_START_DATE,
    PD.EFFECTIVE_END_DATE,

    POA.COUNTRY_CODE,
    POA.COUNTRY_CODE AS COUNTRY,
    POA.LEGAL_ENTITY_ID,
    LOWER(RAWTOHEX(LE.LEGAL_ENTITY_GUID)) AS LEGAL_ENTITY_GUID,
    LE.LEGAL_ENTITY_CODE,
    LE.LEGAL_NAME,
    NVL(LE.SHORT_NAME, LE.LEGAL_NAME) AS LEGAL_ENTITY_DISPLAY,
    LOWER(RAWTOHEX(POA.BUSINESS_UNIT_ID)) AS BUSINESS_UNIT_GUID,
    OU.ORG_UNIT_NAME_EN AS BUSINESS_UNIT_NAME,
    OU.ORG_UNIT_NAME_EN AS BUSINESS_UNIT_DISPLAY,

    PPR.PAY_FREQUENCY_CODE,
    INITCAP(REPLACE(PPR.PAY_FREQUENCY_CODE, '_', '-')) AS PAY_FREQUENCY_DISPLAY,
    CASE PPR.PAY_FREQUENCY_CODE
        WHEN 'WEEKLY'       THEN 52
        WHEN 'BI_WEEKLY'    THEN 26
        WHEN 'SEMI_MONTHLY' THEN 24
        WHEN 'MONTHLY'      THEN 12
        ELSE NULL
    END AS PERIODS_PER_YEAR,
    PPR.DEFAULT_PAYROLL_CALENDAR_ID,
    LOWER(RAWTOHEX(PC.PAYROLL_CALENDAR_GUID)) AS DEFAULT_PAYROLL_CALENDAR_GUID,
    PC.CALENDAR_NAME AS DEFAULT_PAYROLL_CALENDAR_NAME,
    PPR.CURRENCY_CODE,
    PPR.PAYMENT_TIMING,

    PCS.TAX_REGIME_CODE,
    PCS.SOCIAL_SECURITY_SYSTEM_CODE,
    PCS.WORK_WEEK_CODE,
    PCS.LANGUAGE_LOCALE,

    PPS.PAYMENT_METHOD_CODE,
    PPS.COMPENSATION_SOURCE_CODE,
    PPS.TIME_INPUT_SOURCE_CODE,
    PPS.ABSENCE_INPUT_SOURCE_CODE,

    PAO.OFF_CYCLE_PAYMENT_FLAG,
    CASE PAO.OFF_CYCLE_PAYMENT_FLAG
        WHEN 'Y' THEN 'Enabled'
        ELSE 'Disabled'
    END AS OFF_CYCLE_PAYMENT_DISPLAY,
    PAO.RETRO_PAY_PROCESSING_FLAG,
    CASE PAO.RETRO_PAY_PROCESSING_FLAG
        WHEN 'Y' THEN 'Enabled'
        ELSE 'Disabled'
    END AS RETRO_PAY_PROCESSING_DISPLAY,
    PAO.THIRD_PARTY_PAYMENT_FLAG,
    CASE PAO.THIRD_PARTY_PAYMENT_FLAG
        WHEN 'Y' THEN 'Enabled'
        ELSE 'Disabled'
    END AS THIRD_PARTY_PAYMENT_DISPLAY,

    PD.STATUS AS STATUS_CODE,
    INITCAP(PD.STATUS) AS STATUS,
    CASE
        WHEN PD.STATUS = 'ACTIVE'
         AND TRUNC(SYSDATE) BETWEEN TRUNC(PD.EFFECTIVE_START_DATE)
                                AND TRUNC(PD.EFFECTIVE_END_DATE)
        THEN 'Y'
        ELSE 'N'
    END AS ACTIVE_FLAG,

    PD.CREATED_BY,
    PD.CREATION_DATE,
    PD.LAST_UPDATED_BY,
    PD.LAST_UPDATE_DATE
FROM PAY.PAYROLL_DEFINITIONS PD
LEFT JOIN PAY.PAYROLL_ORG_ASSIGNMENTS POA
    ON POA.PAYROLL_ID = PD.PAYROLL_ID
LEFT JOIN PAY.LEGAL_ENTITIES LE
    ON LE.LEGAL_ENTITY_ID = POA.LEGAL_ENTITY_ID
LEFT JOIN ENT.ORG_UNITS OU
    ON OU.ORG_UNIT_ID = POA.BUSINESS_UNIT_ID
LEFT JOIN PAY.PAYROLL_PROCESSING_RULES PPR
    ON PPR.PAYROLL_ID = PD.PAYROLL_ID
LEFT JOIN PAY.PAYROLL_CALENDARS PC
    ON PC.PAYROLL_CALENDAR_ID = PPR.DEFAULT_PAYROLL_CALENDAR_ID
LEFT JOIN PAY.PAYROLL_COMPLIANCE_SETTINGS PCS
    ON PCS.PAYROLL_ID = PD.PAYROLL_ID
LEFT JOIN PAY.PAYROLL_PAYMENT_SETTINGS PPS
    ON PPS.PAYROLL_ID = PD.PAYROLL_ID
LEFT JOIN PAY.PAYROLL_ADVANCED_OPTIONS PAO
    ON PAO.PAYROLL_ID = PD.PAYROLL_ID
