-- =============================================================================
-- FNDSEC.FND_USER_INTEGRATIONS — per-user OAuth provider connections
-- Stores encrypted Google OAuth tokens scoped by ENTERPRISE_ID + USER_ID.
-- Run as FNDSEC (or ADMIN with privileges on FNDSEC objects).
-- =============================================================================

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM all_tables
     WHERE owner = 'FNDSEC'
       AND table_name = 'FND_USER_INTEGRATIONS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE FNDSEC.FND_USER_INTEGRATIONS (
                INTEGRATION_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                ENTERPRISE_ID       NUMBER NOT NULL,
                USER_ID             NUMBER NOT NULL,
                PROVIDER_CODE       VARCHAR2(50) NOT NULL,
                GOOGLE_EMAIL        VARCHAR2(320),
                ACCESS_TOKEN        CLOB,
                REFRESH_TOKEN       CLOB,
                TOKEN_EXPIRY_DATE   TIMESTAMP(6) WITH TIME ZONE,
                TOKEN_SCOPE         VARCHAR2(1000),
                ACTIVE_FLAG         CHAR(1) DEFAULT ''Y'' NOT NULL,
                CONNECTED_DATE      DATE,
                LAST_REFRESH_DATE   DATE,
                CREATED_BY          VARCHAR2(200),
                CREATION_DATE       DATE DEFAULT SYSDATE NOT NULL,
                LAST_UPDATED_BY     VARCHAR2(200),
                LAST_UPDATE_DATE    DATE,
                CONSTRAINT FND_USER_INTEGRATIONS_PK PRIMARY KEY (INTEGRATION_ID),
                CONSTRAINT FND_USER_INTEGRATIONS_UK1 UNIQUE (ENTERPRISE_ID, USER_ID, PROVIDER_CODE),
                CONSTRAINT FND_USER_INTEGRATIONS_CK1 CHECK (ACTIVE_FLAG IN (''Y'', ''N''))
            )';

        EXECUTE IMMEDIATE '
            CREATE INDEX FNDSEC.FND_USER_INTEGRATIONS_N1
                ON FNDSEC.FND_USER_INTEGRATIONS (ENTERPRISE_ID, USER_ID, PROVIDER_CODE, ACTIVE_FLAG)';
    END IF;
END;
/
