/** REC.CANDIDATE_TO_EMPLOYEE_PKG — employee + initial assignment conversion. */
export const PKG = 'REC.CANDIDATE_TO_EMPLOYEE_PKG';
export const VALIDATE_PROC = `${PKG}.VALIDATE_CONVERSION`;
export const CONVERT_PROC = `${PKG}.CONVERT_TO_EMPLOYEE`;

export const LOG_TAG = 'recCandidateConversion';

export const VALIDATE_SUCCESS_MESSAGE = 'Candidate is eligible for employee conversion.';
export const CONVERT_SUCCESS_MESSAGE = 'Candidate converted to employee successfully.';
export const GENERIC_ERROR_MESSAGE = 'Unable to convert candidate to employee. Please try again.';
export const INVALID_OFFER_GUID_MESSAGE =
  'offer_guid must be a 32-character hexadecimal string.';
export const INVALID_CANDIDATE_GUID_MESSAGE =
  'candidate_guid must be a 32-character hexadecimal string.';
export const INVALID_PROBATION_DAYS_MESSAGE = 'Probation days must be zero or greater.';
export const ACCEPTED_OFFER_NOT_FOUND_MESSAGE = 'No accepted offer was found for this candidate.';
export const CANDIDATE_NOT_FOUND_MESSAGE = 'Candidate not found.';

export const CONVERSION_STATUS_COMPLETED = 'COMPLETED';
export const NEXT_ACTION_COMPLETE_ONBOARDING = 'COMPLETE_EMPLOYEE_ONBOARDING';
export const DEFAULT_PROBATION_DAYS = 0;
export const ACCEPTED_OFFER_STATUS = 'ACCEPTED';

/** FNDSEC function code (enforced when REC_ENFORCE_PERMISSIONS=true). */
export const REC_CANDIDATE_CONVERT_EMPLOYEE = 'REC_CANDIDATE_CONVERT_EMPLOYEE';

export const ERROR_CODES = Object.freeze({
  INVALID_OFFER_GUID: 'INVALID_OFFER_GUID',
  INVALID_CANDIDATE_GUID: 'INVALID_CANDIDATE_GUID',
  INVALID_PROBATION_DAYS: 'INVALID_PROBATION_DAYS',
  OFFER_NOT_FOUND: 'OFFER_NOT_FOUND',
  CANDIDATE_NOT_FOUND: 'CANDIDATE_NOT_FOUND',
  ACCEPTED_OFFER_NOT_FOUND: 'ACCEPTED_OFFER_NOT_FOUND',
  OFFER_NOT_ACCEPTED: 'OFFER_NOT_ACCEPTED',
  CANDIDATE_ALREADY_CONVERTED: 'CANDIDATE_ALREADY_CONVERTED',
  OFFER_ALREADY_CONVERTED: 'OFFER_ALREADY_CONVERTED',
  EMPLOYEE_ALREADY_EXISTS: 'EMPLOYEE_ALREADY_EXISTS',
  INVALID_DEPARTMENT: 'INVALID_DEPARTMENT',
  INVALID_POSITION: 'INVALID_POSITION',
  JOB_FAMILY_NOT_CONFIGURED: 'JOB_FAMILY_NOT_CONFIGURED',
  JOB_LEVEL_NOT_CONFIGURED: 'JOB_LEVEL_NOT_CONFIGURED',
  GRADE_NOT_CONFIGURED: 'GRADE_NOT_CONFIGURED',
  INVALID_REPORTING_MANAGER: 'INVALID_REPORTING_MANAGER',
  ASSIGNMENT_CREATION_FAILED: 'ASSIGNMENT_CREATION_FAILED',
  CANDIDATE_CONVERSION_FAILED: 'CANDIDATE_CONVERSION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED'
});
